### ISSUE TITLE
Heartbeat timer?

### ISSUE THREAD

**Issue by JurajPupak** [Microsoft/WebRTC-universal-samples#1]
Hi,
many thanks for example. I would like to ask you, why you send some data from server every 10 seconds? What is the purpose of it?

**Comment by jamescadd** [comment]
The heartbeat is sent to allow presence to function in Chatterbox.  While using the app you'll notice an indicator to the left of the username.  This indicator is green when a user is "online," which is determined by the server based on the timing of the last heartbeat signal from the user's device.
