### ISSUE TITLE
WinRT originate error on accessing skeleton data

### ISSUE THREAD

**Issue by ashikns** [Microsoft/WebRTC-universal-samples#15]
In the CameraStreamCorrelation sample, as soon as you enable skeleton overlay, the log gets spammed with WinRT originate error:

> Exception thrown at 0x00007FFE05C29E08 (KernelBase.dll) in CameraStreamCorrelation.exe: 0x40080201: WinRT originate error (parameters: 0x0000000080000013, 0x000000000000001D, 0x0000009BFDAFEE80).

It doesn't cause any real issues, but it's still annoying for logging and diagnosing purposes. Is there any proper way to prevent this? I've noticed that the error happens when accessing the byte buffer of the skeleton frame.

Running Windows 10 Creator's Update, VS2017 latest, Kinect V2 for WIndows

**Comment by jamescadd** [comment]
Hello, which sample is this referring to? I have not tested with the Kinect camera, is that the only capture device that causes the issue?

Thanks,
James

**Comment by ashikns** [comment]
The sample in question is **CameraStreamCorrelation**. Enable skeleton overlays while running the sample to see the error. It's only purpose is to demonstrate color-to-depth correlation, surely someone must have tested it with the Kinect? 😮

**Comment by jamescadd** [comment]
I think you have confused this repo with another :) this is for our WebRTC samples such as PeerConnection. Let me know if I've misunderstood.

Thanks,
James

**Comment by ashikns** [comment]
Oh boy. I totally feel like an idiot now. My bad I'll post this in the correct one
