### ISSUE TITLE
support WPF?

### ISSUE THREAD

**Issue by fengbozs** [microsoft/WebRTC-universal-samples#17]
Does this project support WPF?

**Comment by jamescadd** [comment]
Hi @fengbozs, the sample is currently a WinRT component and doesn't work in WPF.  We're also working on Desktop .NET support but I don't yet have a timeframe for this (not soon though :).  If you have a need for this I'd like to hear more about the scenarios you're looking to implement.  Thanks!

James

**Comment by Fritzwald** [comment]
Hi @jamescadd, I am also interested in this topic, as we want to use the app on computers that are possibly running Windows XP and Windows 7. In the above message you mentioned you are not close to this yet, this was in January though. Has anything changed regarding the progress?
Or else any recommendation on how this could be achieved otherwise? Any info would be appreciated.

**Comment by Fritzwald** [comment]
Hi @jamescadd, thanks for the update! I will look into the options you wrote about, maybe I'll figure something out. If not it's not a big deal, at some point people should upgrade their PCs 😄

**Comment by qzzf1w** [comment]
Just checking in 8 months later.

Can I use the this universal code 
in a WPF app to do 
webrtc on windows 10?

Is this Possible?

**Comment by jamescadd** [comment]
Hi all - you can find the current progress on the .NET Standard 2.0 version of WebRTC here:
https://github.com/webrtc-uwp/webrtc-uwp-sdk/tree/Robin/m71-dot-net

Note that this currently supports only "headless" clients that do not need to render video or audio.  We're still working on a rendering solution.

**Comment by Lorymi** [comment]
@fengbozs @jamescadd @Fritzwald @qzzf1w 
any news or update for use and stream WebRTC in WPF (Net core 3) ?

**Comment by jamescadd** [comment]
Hello, the most up to date repo is WinRTC.  Please take a look here and post issues as needed.  I'll close this issue as this repo is deprecated.

https://github.com/Microsoft/WinRTC
