### ISSUE TITLE
Alternative WebRTC server

### ISSUE THREAD

**Issue by vaerge** [Microsoft/WebRTC-universal-samples#2]
Hi -

Thank you for this project. Trying to get it to run on Windows 10 IoT on a Raspberry Pi 3 - and that has gone well - I think. I cannot get two clients to connect to a room, only one. 

I'm trying to use the sample as-is, and see that it use the demo of the apprtc server. I don't know if that is the reason why I cannot connect two clients/peers to the same room. (in fact, I cannot even do it directly on the app.tc website, with two different devices). Any clue as to why this is happening? 

Thanks,
Anders

**Comment by jamescadd** [comment]
Hi Anders,

We haven't fully tested the AppRTC sample on Raspberry Pi.  I would recommend trying the recently added PeerCC sample which is more lightweight.  If this is something you're still interested in let me know and we can reopen the issued.  I'd like to hear more about your use case and the cameras you're trying to use with the sample if you can share.

Thanks,
James
