### ISSUE TITLE
Org.WebRtc miss in PeerCCUnity

### ISSUE THREAD

**Issue by peptrig** [Microsoft/WebRTC-universal-samples#21]
Hi all,

I tried to build in Unity **PeerCCUnity** project to UWP platform but I have the follow error:

**ArgumentException: The Assembly Org.WebRtc is referenced by PeerConnectionClientCore ('Assets/Plugins/WSA/PeerConnectionClientCore.dll'). But the dll is not allowed to be included or could not be found.**

So I copied the dll from the path "PeerCC-Sample\Output\PeerCC.ClientUnityD3D\WebRtc\bin\x86\Debug" into the path "PeerCCUnity\Assets\Plugins\WSA" but I have another error when I build:

**UnityException: Failed to run reference rewriter with command --target="Temp\StagingArea\PeerConnectionClientCore.dll"**

Do you know how to solve?

**Comment by Fritzwald** [comment]
Hi peptrig,

I had the same problem. In the folder where you found the Org.WebRtc.dll there is also a file called Org.WebRtc.winmd which goes in the same folder in the Unity project. Hopefully this helps you as well.

**Comment by peptrig** [comment]
Thank you very much @Fritzwald, I solved. You're right.

**Comment by JairoGLoz** [comment]
@peptrig did you host the peerconnection_server.exe on an azure windows 10 VM? I tried to run the server on a PC connected to local network but I'm not able to connect with the hololens app. I'm trying to host the server on an azure VM but now I'm having trouble installing Visual Studio on it to solve missing .dll related problems when running the exe.

Any advice would be very appreciated.

Thanks in advance.
