### ISSUE TITLE
Cannot build WebRtcUnityD3D

### ISSUE THREAD

**Issue by chinmayabhat** [Microsoft/WebRTC-universal-samples#23]
Hi,

I'm unable to build the D3D Solution. After the build, the following is shown.
========== Rebuild All: 8 succeeded, 1 failed, 0 skipped ==========

I deployed the Unity D3D app to the Hololens. Using the PeerCC-sample on my desktop, I was able to see MRC content from the Hololens on the PeerCC desktop client, but was not able to see remote and local video in the Hololens Unity app. I'm assuming it's because of the incomplete D3D build.  Any guidance would be helpful.

Here is the Output log when I build WebRtcUnityD3D using Release in x86 mode.

1>------ Rebuild All started: Project: WebRtc.Stats.Observer, Configuration: Release Win32 ------
2>------ Rebuild All started: Project: WebRtc.UWP.Native.Builder, Configuration: Release Win32 ------
3>------ Rebuild All started: Project: MediaEngineUWP, Configuration: Release Win32 ------
4>------ Rebuild All started: Project: WebRtcScheme, Configuration: Release Win32 ------
1>Running message compiler on ..\..\..\org\webrtc\stats\etw_providers.man
2>
2>[92mRunning prepare script ...[0m
2>
2>[93mRunning script parameters:[0m
2>[93mTarget: webrtc[0m
2>[93mPlatform: x86[0m
2>[93mLog level: 4[0m
2>[93mPreparing webrtc development environment ...[0m
2>[93mPreparing development environment for x86 platform...[0m
1>webrtc_stats_network_sender.cpp
1>webrtc_stats_observer.cpp
2>depotToolsPathCheck entered...
2>Python is present.
2>
2>[92mRunning WebRTC prepare script ...[0m
2>[92m=================================[0m
2>[93mPreparing WebRTC development environment for x86 platform ...[0m
2>Executing prepareWebRTC function
2>Pushed webrtc\xplatform\webrtc path
2>Executing generateChromiumFolders function
2>chromium\src folder already exists
2>chromium\src\tools folder already exists
3>MediaEngine.cpp
2>chromium\src\third_party folder already exists
2>chromium\src\third_party\winsdk_samples folder already exists
2>chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
2>third_party folder already exists
2>tools folder already exists
2>Executing makeJunctionLinks function
2>Path "buildtools" already exists
2>Path "build" already exists
4>SchemeHandler.cpp
2>Path "chromium\src\third_party\jsoncpp" already exists
2>Path "chromium\src\third_party\jsoncpp\source" already exists
2>Path "chromium\src\tools\protoc_wrapper" already exists
2>Path "chromium\src\third_party\protobuf" already exists
2>Path "chromium\src\third_party\yasm" already exists
2>Path "chromium\src\third_party\opus" already exists
2>Path "chromium\src\third_party\boringssl" already exists
2>Path "chromium\src\third_party\usrsctp" already exists
2>Path "chromium\src\third_party\libvpx" already exists
2>Path "chromium\src\third_party\libvpx\source\libvpx" already exists
2>Path "chromium\src\testing" already exists
2>Path "testing" already exists
2>Path "tools\protoc_wrapper" already exists
2>Path "third_party\yasm" already exists
2>Path "third_party\yasm\binaries" already exists
2>Path "third_party\yasm\source\patched-yasm" already exists
2>Path "third_party\opus" already exists
2>Path "third_party\opus\src" already exists
2>Path "third_party\boringssl" already exists
2>Path "third_party\boringssl\src" already exists
2>Path "third_party\usrsctp" already exists
2>Path "third_party\usrsctp\usrsctplib" already exists
2>Path "third_party\protobuf" already exists
2>Path "chromium\src\third_party\expat" already exists
2>Path "third_party\expat" already exists
2>Path "chromium\src\third_party\googletest" already exists
2>Path "third_party\googletest" already exists
2>Path "third_party\googletest\src" already exists
2>Path "third_party\libsrtp" already exists
2>Path "third_party\libvpx" already exists
2>Path "third_party\libyuv" already exists
2>Path "third_party\openmax_dl" already exists
2>Path "third_party\libjpeg_turbo" already exists
2>Path "third_party\jsoncpp" already exists
2>Path "third_party\winuwp_compat" already exists
2>Path "third_party\winuwp_h264" already exists
2>Path "third_party\gflags" already exists
2>Path "third_party\gflags\src" already exists
2>Path "third_party\winsdk_samples" already exists
2>Path "tools\gyp" already exists
2>Path "tools\clang" already exists
2>        1 file(s) copied.
2>        1 file(s) copied.
2>        1 file(s) copied.
2>        1 file(s) copied.
4>   Creating library C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\WebRtcScheme\WebRtcScheme.lib and object C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\WebRtcScheme\WebRtcScheme.exp
4>Generating code
2>0> File buildtools\win\gn.exe exists and SHA1 matches. Skipping.
2>Success!
2>Downloading 1 files took 0.020000 second(s)
2>0> File buildtools\win\clang-format.exe exists and SHA1 matches. Skipping.
2>Success!
2>Downloading 1 files took 0.103000 second(s)
2>Executing generateProjects function
2>[93mGenerating WebRTC projects for x86 platform ...[0m
4>All 394 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
4>Finished generating code
2>out\winuwp_10_x86_debug folder already exists
2>Copied
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEngine.cpp(15): warning C5043: 'SafeString::SafeString': exception specification does not match previous declaration
3>c:\ortclib\common\windows\samples\peercc\mediaengineplayerplugin\mediaengineuwp\shared\MediaEngine.h(192): note: see declaration of 'SafeString::SafeString'
3>MediaHelpers.cpp
3>MediaEnginePlayer.cpp
3>dllmain.cpp
4>WebRtcScheme.vcxproj -> C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\WebRtcScheme\WebRtcScheme.dll
4>Target Plugin Path is C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\WebRtcScheme\..\..\ClientUnity\Unity\PeerCCUnity\Assets\
4>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\WebRtcScheme\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins already exists.
4>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\WebRtcScheme\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA already exists.
4>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\WebRtcScheme\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA\x86 already exists.
4>        1 file(s) copied.
4>        1 file(s) copied.
4>        1 file(s) copied.
**5>------ Rebuild All started: Project: peerconnection_server, Configuration: Release Win32 ------
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\dllmain.cpp(65): warning C4447: 'main' signature found without threading model. Consider using 'int main(Platform::Array<Platform::String^>^ args)'.
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(324): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(325): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(472): warning C4244: 'argument': conversion from 'UINT32' to 'float', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(487): warning C4244: 'argument': conversion from 'UINT32' to 'float', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(769): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(770): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(771): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
3>C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\Shared\MediaEnginePlayer.cpp(772): warning C4244: '=': conversion from 'float' to 'LONG', possible loss of data
5>ninja : error : unknown target './peerconnection_server.exe'
5>Cleaning... 0 files.
5>C:\ortclib\webrtc\windows\projects\msvc\PeerConectionServer\peerconnection_server.vcxproj(98,5): error MSB3073: The command "call C:\ortclib\webrtc\windows\projects\msvc\PeerConectionServer\..\..\..\..\xplatform\depot_tools\ninja.exe -C C:\ortclib\webrtc\windows\projects\msvc\PeerConectionServer\..\..\..\..\xplatform\webrtc\out\win_x86_Release\ -tclean ./peerconnection_server.exe" exited with code 1.
5>Done building project "peerconnection_server.vcxproj" -- FAILED.**
3>   Creating library C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\MediaEngineUWP\MediaEngineUWP.lib and object C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\MediaEngineUWP\MediaEngineUWP.exp
3>Generating code
3>All 1400 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
3>Finished generating code
3>MediaEngineUWP.vcxproj -> C:\ortclib\webrtc\windows\solutions\Build\Output\x86\Release\MediaEngineUWP\MediaEngineUWP.dll
3>Target Plugin Path is C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\Client\Unity\UnityVideoControl\Assets\
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\Client\Unity\UnityVideoControl\Assets\Plugins already exists.
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\Client\Unity\UnityVideoControl\Assets\Plugins\WSA already exists.
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\Client\Unity\UnityVideoControl\Assets\Plugins\WSA\x86 already exists.
3>        1 file(s) copied.
3>        1 file(s) copied.
3>Target Plugin Path is C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\ClientUnity\Unity\PeerCCUnity\Assets\
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins already exists.
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA already exists.
3>A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\MediaEnginePlayerPlugin\MediaEngineUWP\UWP\..\..\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA\x86 already exists.
3>        1 file(s) copied.
3>        1 file(s) copied.
3>Done building project "MediaEngineUWP.vcxproj".
1>RC : warning RC4005: '_HAS_EXCEPTIONS' : redefinition
1>
1>WebRtc.Stats.Observer.vcxproj -> C:\ortclib\webrtc\windows\solutions\Build\Output\WebRtc.Stats.Observer\Release\x86\lib\WebRtc.Stats.Observer.lib
1>Done building project "WebRtc.Stats.Observer.vcxproj".
2>Generating Visual Studio projects took 2069ms
2>Done. Made 465 targets from 117 files in 55987ms
2>Copied
2>out\winuwp_10_x86_release folder already exists
2>Copied
2>Generating Visual Studio projects took 2498ms
2>Done. Made 465 targets from 117 files in 56798ms
2>Copied
2>Popped webrtc\xplatform\webrtc path
2>
2>[92mSuccess: WebRTC development environment is prepared.[0m
2>=======   WebRTC prepare script summary   =======
2>=======   platform   =========   result   =======
2>[93m            arm                 not run[0m
2>[93m            x64                 not run[0m
2>[92m            x86                 prepared[0m
2>[93m            win32               not run[0m
2>=================================================
2>
2>
2>[92mSuccess: Development environment is set.[0m
2>restorePathEnv entered...
2>Number of paths temporarily removed from environment PATH: 0
2>[93mTotal execution time: 00:02:36 (156s total)[0m
2>
2>
2>[92mRunning prepare script ...[0m
2>
2>[93mRunning script parameters:[0m
2>[93mTarget: webrtc[0m
2>[93mPlatform: win32[0m
2>[93mLog level: 4[0m
2>[93mPreparing webrtc development environment ...[0m
2>[93mPreparing development environment for win32 platform...[0m
2>depotToolsPathCheck entered...
2>Python is present.
2>
2>[92mRunning WebRTC prepare script ...[0m
2>[92m=================================[0m
2>[93mPreparing WebRTC development environment for win32 platform ...[0m
2>Executing prepareWebRTC function
2>Pushed webrtc\xplatform\webrtc path
2>Executing generateChromiumFolders function
2>chromium\src folder already exists
2>chromium\src\tools folder already exists
2>chromium\src\third_party folder already exists
2>chromium\src\third_party\winsdk_samples folder already exists
2>chromium\src\third_party\libjingle\source\talk\media\testdata\ folder already exists
2>third_party folder already exists
2>tools folder already exists
2>Executing makeJunctionLinks function
2>Path "buildtools" already exists
2>Path "build" already exists
2>Path "chromium\src\third_party\jsoncpp" already exists
2>Path "chromium\src\third_party\jsoncpp\source" already exists
2>Path "chromium\src\tools\protoc_wrapper" already exists
2>Path "chromium\src\third_party\protobuf" already exists
2>Path "chromium\src\third_party\yasm" already exists
2>Path "chromium\src\third_party\opus" already exists
2>Path "chromium\src\third_party\boringssl" already exists
2>Path "chromium\src\third_party\usrsctp" already exists
2>Path "chromium\src\third_party\libvpx" already exists
2>Path "chromium\src\third_party\libvpx\source\libvpx" already exists
2>Path "chromium\src\testing" already exists
2>Path "testing" already exists
2>Path "tools\protoc_wrapper" already exists
2>Path "third_party\yasm" already exists
2>Path "third_party\yasm\binaries" already exists
2>Path "third_party\yasm\source\patched-yasm" already exists
2>Path "third_party\opus" already exists
2>Path "third_party\opus\src" already exists
2>Path "third_party\boringssl" already exists
2>Path "third_party\boringssl\src" already exists
2>Path "third_party\usrsctp" already exists
2>Path "third_party\usrsctp\usrsctplib" already exists
2>Path "third_party\protobuf" already exists
2>Path "chromium\src\third_party\expat" already exists
2>Path "third_party\expat" already exists
2>Path "chromium\src\third_party\googletest" already exists
2>Path "third_party\googletest" already exists
2>Path "third_party\googletest\src" already exists
2>Path "third_party\libsrtp" already exists
2>Path "third_party\libvpx" already exists
2>Path "third_party\libyuv" already exists
2>Path "third_party\openmax_dl" already exists
2>Path "third_party\libjpeg_turbo" already exists
2>Path "third_party\jsoncpp" already exists
2>Path "third_party\winuwp_compat" already exists
2>Path "third_party\winuwp_h264" already exists
2>Path "third_party\gflags" already exists
2>Path "third_party\gflags\src" already exists
2>Path "third_party\winsdk_samples" already exists
2>Path "tools\gyp" already exists
2>Path "tools\clang" already exists
2>        1 file(s) copied.
2>        1 file(s) copied.
2>        1 file(s) copied.
2>        1 file(s) copied.
2>0> File buildtools\win\gn.exe exists and SHA1 matches. Skipping.
2>Success!
2>Downloading 1 files took 0.015000 second(s)
2>0> File buildtools\win\clang-format.exe exists and SHA1 matches. Skipping.
2>Success!
2>Downloading 1 files took 0.009000 second(s)
2>Executing generateProjects function
2>[93mGenerating WebRTC projects for win32 platform ...[0m
2>out\win_x86_debug folder already exists
2>Copied
2>Generating Visual Studio projects took 2185ms
2>Done. Made 479 targets from 120 files in 32447ms
2>Copied
2>out\win_x86_release folder already exists
2>Copied
2>Generating Visual Studio projects took 2235ms
2>Done. Made 479 targets from 120 files in 28950ms
2>Copied
2>Popped webrtc\xplatform\webrtc path
2>
2>[92mSuccess: WebRTC development environment is prepared.[0m
2>=======   WebRTC prepare script summary   =======
2>=======   platform   =========   result   =======
2>[93m            arm                 not run[0m
2>[93m            x64                 not run[0m
2>[93m            x86                 not run[0m
2>[92m            win32               prepared[0m
2>=================================================
2>
2>
2>[92mSuccess: Development environment is set.[0m
2>restorePathEnv entered...
2>Number of paths temporarily removed from environment PATH: 0
2>[93mTotal execution time: 00:01:30 (90s total)[0m
2>
2>[92mWebrtc build is started. It will take couple of minutes.[0m
2>[92mWorking ...[0m
2>[92mx86[0m
2>[92mPlatform x86[0m
2>Visual Studio path is "C:\Program
2>Visual Studio 2017 Tools MSVC Version is 14.12.25827
2>Determining compiler options ...
2>CPU arhitecture is x64
2>Selected compiler option is amd64_x86
2>[93mBuilding webrtc native libs[0m
2>ninja: no work to do.
2>[93mBuilding webrtc/rtc_base:rtc_json native lib[0m
2>ninja: no work to do.
2>Source path is "C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\"
2>Destination path is C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\..\..\WEBRTC_BUILD\webrtc\Release\x86\
2>**********************************************************************
2>** Visual Studio 2017 Developer Command Prompt v15.5.7
2>** Copyright (c) 2017 Microsoft Corporation
2>**********************************************************************
2>[vcvarsall.bat] Environment initialized for: 'x64_x86'
2>Microsoft (R) Library Manager Version 14.12.25835.0
2>Copyright (C) Microsoft Corporation.  All rights reserved.
2>
2>Copying dlls from C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\ to C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\..\..\WEBRTC_BUILD\webrtc\Release\x86\
2>Copying pdbs from C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\ to C:\ortclib\webrtc\xplatform\webrtc\out\winuwp_10_x86_release\..\..\WEBRTC_BUILD\webrtc\Release\x86\
2>
2>[92mSuccess:  WebRtc library is built successfully.[0m
2>
2>[93mTotal execution time: 00:00:27 (27s total)[0m
6>------ Rebuild All started: Project: Org.WebRtc.Uwp, Configuration: Release Win32 ------
6>DataChannel.cc
6>GlobalObserver.cc
6>Marshalling.cc
6>Media.cc
6>MediaSourceHelper.cc
6>PeerConnectionInterface.cc
6>RTMediaStreamSource.cc
6>WinUWPDeviceManager.cc
6>   Creating library C:\ortclib\webrtc\windows\solutions\Build\Output\Org.WebRtc.Uwp\Release\x86\Org.WebRtc.lib and object C:\ortclib\webrtc\windows\solutions\Build\Output\Org.WebRtc.Uwp\Release\x86\Org.WebRtc.exp
6>Org.WebRtc.Uwp.vcxproj -> C:\ortclib\webrtc\windows\solutions\Build\Output\Org.WebRtc.Uwp\Release\x86\Org.WebRtc.dll
6>Target Plugin Path is C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\Client\Unity\UnityVideoControl\Assets\
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\Client\Unity\UnityVideoControl\Assets\Plugins already exists.
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\Client\Unity\UnityVideoControl\Assets\Plugins\WSA already exists.
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\Client\Unity\UnityVideoControl\Assets\Plugins\WSA\x86 already exists.
6>        1 file(s) copied.
6>        1 file(s) copied.
6>        1 file(s) copied.
6>Target Plugin Path is C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\ClientUnity\Unity\PeerCCUnity\Assets\
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\ClientUnity\Unity\PeerCCUnity\Assets\Plugins already exists.
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA already exists.
6>A subdirectory or file C:\ortclib\webrtc\windows\projects\msvc\Org.WebRtc.Uwp\..\..\..\..\..\common\windows\samples\PeerCC\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA\x86 already exists.
6>        1 file(s) copied.
6>        1 file(s) copied.
6>        1 file(s) copied.
7>------ Rebuild All started: Project: PeerConnectionClientUnityD3DCore, Configuration: Release x86 ------
7>  PeerConnectionClientUnityD3DCore -> C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.CoreUnityD3D\WebRtc\bin\x86\Release\PeerConnectionClientCore.dll
7>  Target Plugin Path is C:\ortclib\common\windows\samples\PeerCC\ClientCore\..\ClientUnity\Unity\PeerCCUnity\Assets\
7>  A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\ClientCore\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins already exists.
7>  A subdirectory or file C:\ortclib\common\windows\samples\PeerCC\ClientCore\..\ClientUnity\Unity\PeerCCUnity\Assets\Plugins\WSA already exists.
7>          1 file(s) copied.
7>  The system cannot find the file specified.
7>          1 file(s) copied.
8>------ Rebuild All started: Project: Assembly-CSharp, Configuration: Release x86 ------
8>  Running SerializationWeaver...
8>  Symbols will be read from ..\..\..\Unity\Unprocessed\UnityEngine.CoreModule.pdb
8>  Symbols will be read from C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D.Assembly-CSharp\WebRtc\bin\x86\Release\Unprocessed\Assembly-CSharp.pdb
8>  Symbols will be read from C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D.Assembly-CSharp\WebRtc\bin\x86\Release\Unprocessed\Assembly-CSharp.pdb
8>  Script Module: Assembly-CSharp.dll
8>  Pass: 0 took 6 milliseconds
8>  Pass: 1 took 28 milliseconds
8>  Symbols will be read from C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D.Assembly-CSharp\WebRtc\bin\x86\Release\Unprocessed\Assembly-CSharp.pdb
8>  Weaving assembly C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D.Assembly-CSharp\WebRtc\bin\x86\Release\Unprocessed\Assembly-CSharp.dll
8>   + ControlScript
8>   + GazeGestureManager
8>   + WorldCursor
8>  Will export symbols of pdb format
8>  SerializationWeaver done.
8>  Assembly-CSharp -> C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D.Assembly-CSharp\WebRtc\bin\x86\Release\Assembly-CSharp.dll
9>------ Rebuild All started: Project: PeerConnectionClientUnity, Configuration: Release x86 ------
9>C:\ortclib\common\windows\samples\PeerCC\ClientUnity\App.cs(56,13,56,71): warning CS0618: 'ApplicationView.SuppressSystemOverlays.set' is obsolete: 'Use the TryEnterFullScreen method and IsFullScreenMode property instead of SuppressSystemOverlays. For more info, see MSDN.'
9>  PeerConnectionClientUnity -> C:\ortclib\common\windows\samples\PeerCC\Output\PeerCC.ClientUnityD3D\WebRtc\bin\x86\Release\PeerConnectionClientUnity.exe
9>  UnityWSAPlayerDir "C:\Program Files\Unity\Editor\Data\PlaybackEngines\MetroSupport\".
9>  UnityProjectDir "".
9>  Copying unprocessed assemblies...
9>  Running AssemblyConverter...
9>  AssemblyConverter done.
9>  Modifying AppxPackagePayload
========== Rebuild All: 8 succeeded, 1 failed, 0 skipped ==========

The error list is as below.

Error	MSB3073	The command "call C:\ortclib\webrtc\windows\projects\msvc\PeerConectionServer\..\..\..\..\xplatform\depot_tools\ninja.exe -C C:\ortclib\webrtc\windows\projects\msvc\PeerConectionServer\..\..\..\..\xplatform\webrtc\out\win_x86_Release\ -tclean ./peerconnection_server.exe" exited with code 1.

**Comment by jamescadd** [comment]
We think there may have been an issue related to depending on the Unity version 4.0f which is no longer available.  This branch is updated to 4.1f if you want to give it a try: https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2FWebRTC-universal-samples%2Fissues%2F21%23issuecomment-402063524&data=02%7C01%7Cjacadd%40microsoft.com%7C273cdf24ed04478f1e4608d5e0c29397%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636662048665080890&sdata=D912A2xuRj3EOrEv1zfA7%2BZF3kLltyfAekou%2FqkhLaU%3D&reserved=0

**Comment by chinmayabhat** [comment]
Thanks @jamescadd. I made a fresh clone of the project and used Unity 4.1f. The issue doesnt come up anymore. Thanks for your help!
