### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by Fritzwald** [Microsoft/WebRTC-universal-samples#24]
Hi all!

I am trying to use the PeerCC sample on two hololenses. They can both connect to the server and see each other in the list. However, when I press call they both crash. When debugging I get this error:

**An unhandled exception of type 'System.AccessViolationException' occurred in PeerCC.
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.**

I am unsure what could cause this, maybe someone has an idea.

Thank you in advance!

**Comment by jamescadd** [comment]
I haven't actually tried this across two HoloLenses. Are you able to connect from a HoloLens to a PC without issue, either with Unity or UWP client on the PC?

**Comment by Fritzwald** [comment]
Hi James, 
Thanks for the reply. I have managed to make it work between PC and Hololens, but only after recompiling the dll's and reimporting them into the unity project. I imagine there was a hiccup somewhere, possibly relating to the multiple solutions in the same folder.
