### ISSUE TITLE
Missing namespace: UnityPlayer, WinRTBridge, AppCallBacks.

### ISSUE THREAD

**Issue by sammytran90** [Microsoft/WebRTC-universal-samples#26]
hi, I'm interested in WebRTC with Hololens. I tried to build WebRTC.UnityD3D on Visual Studio 2017 ( **Release / x86** build mode) following the instruction but I failed and received errors telling that: **UnityPlayer, WinRTBridge, AppCallBacks** namespaces were missing. Do you have any suggestion? I look forward for your response.
Thanks.

**Comment by sammytran90** [comment]
Hi, I was able to build WebRTC.UnityD3D on Hololens and finally connected to a ice server and saw peer from windows (PC). However, when I made a call, exception as below thrown:
**Exception thrown: 'System.MissingMethodException' in Assembly-CSharp.dll
Method not found: 'Windows.Media.Core.IMediaSource Org.WebRtc.Media.CreateMediaStreamSource(Org.WebRtc.MediaVideoTrack, System.String, System.String)'.**

Do you have any idea why IMediaSource is not found in the project? I would be appreciated.

**Comment by jamescadd** [comment]
This is likely related to an incorrect tools version.  Give this branch a try (noting the version of Unity required) and let me know if it fixes the issue: https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity

**Comment by sammytran90** [comment]
thanks @jamescadd . I'm playing with https://github.com/ortclib/ortclib-sdk/tree/Mosa/20180320-peercc-unity already. I will response my results. :)
