### ISSUE TITLE
peerconnection_server requires debug runtimes

### ISSUE THREAD

**Issue by stjohn909** [Microsoft/WebRTC-universal-samples#31]
Missing  MSVCP140D.dll error on test machine without Visual Studio installed.  Runs fine on dev machine.

**Comment by Jelop** [comment]
Hi, I had the same issue and I fixed it by copying the file from C:\Windows\SysWOW64 on my machine to the test machine. There were two other files that were needed as well so I copied them from the same place. I put the files in the same folder as the server but I expect putting them in SysWOW64 on the test machine would work as well.

**Comment by jamescadd** [comment]
Thanks @stjohn909 - the repo you linked is the repo of record, this is a just a mirror of that code.  I need to update the exe here with a release version to fix the issue.

**Comment by markgrossnickle** [comment]
For anyone else that stumbles onto this issue as I don't believe a new exe has been uploaded to the project.  This is a x64 release build and it runs correctly. 

[peerconnection_server.zip](https://github.com/Microsoft/WebRTC-universal-samples/files/2891573/peerconnection_server.zip)

**Comment by jamescadd** [comment]
Thanks @markgrossnickle - updated the binary in the repo.
