### ISSUE TITLE
Access to peerconnection_server source code?

### ISSUE THREAD

**Issue by Fritzwald** [Microsoft/WebRTC-universal-samples#32]
Hi!

I'm wondering if there is any way to get access to the source code of the peerconnection_server instead of just a built version, as I'm interested in some of its functionalities. 

Thanks in advance!

**Comment by jamescadd** [comment]
Hello, the source is available [here](https://github.com/webrtc-uwp/webrtc/tree/68457f70115fc2ce11a14f2f262e13577b5051e7/webrtc/examples/peerconnection/server).  You can follow the instructions to build this [repo](https://github.com/webrtc-uwp/webrtc-uwp-sdk) to get a solution file that will build it.  There's also a version that runs in Azure available [here](https://github.com/anastasiia-zolochevska/signaling-server) though you should note there is a heartbeat issue that impacts PeerCC (see the issues for the repo).

**Comment by Fritzwald** [comment]
Hi @jamescadd , I don't think I understand how you go from using the source code in the first link you sent to building the server in the second repo. Using the second repo I can build the server, however there is no way to edit it, the project in the solution is empty. 
How do I get the code from the other repository where I can see the actual files into the solution to change it and then build it?
Thanks for the help.
