### ISSUE TITLE
How to close HololensCamera

### ISSUE THREAD

**Issue by alnegod1** [Microsoft/WebRTC-universal-samples#41]
Hi,sir；
I had a successful video call with the PC client using HoloLens‘
when I disconnected the Called, PC client's camera turn off,ButHololens'external camera wouldn't shut down.I had eproduce it in a Debug build running on HL,Here is  the VS output.When I disconnected the Called,
![1539142164 1](https://user-images.githubusercontent.com/39084297/46711640-cc948b00-cc7f-11e8-9606-bbd88341672e.jpg)
Here are some others VS output:
[OutPut.txt](https://github.com/Microsoft/WebRTC-universal-samples/files/2463040/OutPut.txt)
Thanks

**Comment by Fritzwald** [comment]
Hi @alnegod1, have you added
```
<Extensions>
   <Extension Category="windows.activatableClass.inProcessServer">
      <InProcessServer>
        <Path>WebRtcScheme.dll</Path>
        <ActivatableClass ActivatableClassId="WebRtcScheme.SchemeHandler" ThreadingModel="both" />
      </InProcessServer>
   </Extension>
</Extensions> 
```


to the Package.appxmanifest file?

**Comment by alnegod1** [comment]
Yes,I had added it 
![1539222572 1](https://user-images.githubusercontent.com/39084297/46775727-01b1e380-cd3b-11e8-8277-18529e4fdba2.jpg)
Could you help me build a good APPx for hololens used this sample:WebRTC-universal-samples/Samples/PeerCC-Sample/ClientUnity/Unity/PeerCCUnity?Because I don't know if that example is good or bad

**Comment by Fritzwald** [comment]
Ok so if that was not the problem then I recommend you look through issue #40 and check the things I and, more importantly, **mingalll** have said. For example rebuild **PeerConnectionClient.WebRtc.UnityD3D.sln** to reimport the dll's into Unity. 
The sample usually works very well, there's just some hiccups sometimes.

**Comment by alnegod1** [comment]
I had rebuild it many times;Everything is OK ;I only build it with Unity 2017.4.8;Is that why?

**Comment by Fritzwald** [comment]
It might be. I personally use 2017.4.2 where it works, so it might be worth a try.
