### ISSUE TITLE
Extracting Primitive Pose Data

### ISSUE THREAD

**Issue by Fritzwald** [Microsoft/WebRTC-universal-samples#42]
Hi all!
I am wondering how the CameraProjectionTransform and CameraViewTransform can be extracted from the IMFSample* I have access to after following the necessary steps. 
Help would be appreciated.

**Comment by Fritzwald** [comment]
Actually I figured it out eventually. It requires you to use `GetBlob()` on the IMFSample*, with which you can access extrinsics and intrinsics. 
However I ran into a different different problem. Usually PeerConnection uses `Media.CreatMedia().CreateMediaStreamSource(_selfVideoTrack, type, "SELF");` to create a Media Stream to send to the peer. However if I try to 
`Media media = Media.CreateMedia();`
`MFSampleVideoSource mfSampleSource = media.CreateMFSampleVideoSource();
mfSampleSource.OnMFSampleVideoFrame += (s) => {
    Debug.WriteLine("MfSample received: " + s);
};`
first it does not work. Can these two systems not coexist?

**Comment by jamescadd** [comment]
Hello, it's been awhile so I wanted to check if this was still an outstanding issue.

**Comment by Fritzwald** [comment]
Not this issue exactly, so I will close this one. The problem in my second comment solved itself once I fexed something else.
