### ISSUE TITLE
Cannot build the project with SDK 17134, Cannot run with 16299

### ISSUE THREAD

**Issue by HarryPKay** [Microsoft/WebRTC-universal-samples#55]
Hi, I have issues making this work.

## First Try with SDK 17134

First, I could not build the "PeerConnectionClientUnity" project in Visual Studio 2017.
I have Unity 2017.4.1 installed with .NET Scripting Backend.
When I opened the solution I had to retarget everything to newer SDK 1713, which was recommended for this project.

The problem appears while building Assebly-CSharp project, where SerialisationWeaver exits with code 1. I used that same command and found out that it is missing project.lock.json file. This file does not exist at the desired location. I found out that the project.json disappears when retargeting the solution.

## Second Try with SDK 16299

So, I installed the Windows SDK 16299 which is the original one for the downloaded project. This time, I could succesfully build and deploy project to the Hololens, but the application does not start properly. All I see is a blue window.

Any advice?

**Comment by alnegod1** [comment]
我可以用汉语回复你吗//
