### ISSUE TITLE
About how to set or change the bit rate ?

### ISSUE THREAD

**Issue by alnegod1** [Microsoft/WebRTC-universal-samples#56]
hello, Could you help me? How to set or change the bit rate of video transmitted from HoloLens to PC by using webrtc for HoloLens and PC video communication

**Comment by jamescadd** [comment]
I see that you closed the issue, were you able to adjust the bitrate? My recommendation would be to try something like the following though I'm not certain it will work:
https://webrtchacks.com/limit-webrtc-bandwidth-sdp/
