### ISSUE TITLE
Unity Hololens client app crashes 

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [Microsoft/WebRTC-universal-samples#62]
Hi,
Unity Hololens client app crashes when starting call to PC client. Please see below error:

Exception thrown: 'System.AccessViolationException' in PeerCCUnity.exe
An unhandled exception of type 'System.AccessViolationException' occurred in PeerCCUnity.exe
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

When I use Unity UWP app - everything works fine.
Before crash I can see red Hololens Video Recording icon in the upper-left corner.

Thanks in advance for help.

**Comment by jamescadd** [comment]
Hello, are you able to run from Visual Studio and post the console output?  Make sure to build in debug and enable mixed mode debugging.

**Comment by TomaszWozniakMosina** [comment]
Hi,

Thanks for quick response.
Please see attached files with console output.

[WebRtcErrorLog.txt](https://github.com/Microsoft/WebRTC-universal-samples/files/2836132/WebRtcErrorLog.txt)
[WebRtcErrorLog_MixedMode.txt](https://github.com/Microsoft/WebRTC-universal-samples/files/2836133/WebRtcErrorLog_MixedMode.txt)

**Comment by TomaszWozniakMosina** [comment]
Selection H.264 didn't solve the problem :(

**Comment by TomaszWozniakMosina** [comment]
I have build two Unity clients without Mixed Reality to run on two local PCs.
Result was:
Applications didn't crash after connecting, however there was no video and after a while I had an error (please see attached screen).
![accessmemoryexception_webrtc](https://user-images.githubusercontent.com/29869511/52407498-c77e0600-2ad0-11e9-8109-d7418e938bc3.PNG)

**Comment by TomaszWozniakMosina** [comment]
I have found this description of the issue:
[PeerCCUnity Hololens app crashes after 2-4 seconds of video-call](https://github.com/Microsoft/WebRTC-universal-samples/issues/28)
Seems similar to my issue.
Could you please confirm that [here](https://github.com/Microsoft/WebRTC-universal-samples/tree/master/Samples/PeerCC-Sample) I can find code that is free from this bug? I assumed that since Aug 24, 2018 the code was updated, but please correct me if I'm wrong.
Thanks in advance for help.

**Comment by jamescadd** [comment]
Sorry to make you dig through the bugs - we're nearing a point where we can update this sample and the NuGet package to a newer build and have things work a bit more cleanly.  Currently the last "definitely working" build can be pulled from here:

git clone --recursive -b Mosa/20180320-peercc-unity https://github.com/ortclib/ortclib-sdk.git ortclib-sdk-m62
CD ortclib-sdk-m62
bin\prepare.bat -logLevel 4

Keep in mind you need the older Unity toolchain as described in the docs.  If you hit any issues post the prepare output or VS build output.

If you want to try a newer version with Unity 2018 tooling just release the branch above with releases/m62.  Note that it has an issue where you need to long-press the buttons for the clicks to register (I hold them down for about 3 seconds).  I need to run this again and ensure it's working though, there may still be issues to sort out.  Right now we're focusing on getting the Unity support up to M66 & M71 with newer Unity tooling so this is just a step along the way.

**Comment by TomaszWozniakMosina** [comment]
Hi again :)
This time I had build as you mentioned above, effect is the same - Unity client crashes or there is no video shown and app doesn't crash (it happened when I were in remote debug mode).
However logs seems different (I cannot see 'AccessViolationException' - please see in attachment.
I also added logs from the other client app- when I were in remote debug mode, apps didn't crash, on Local Client I saw only 'small' preview video.
Thanks in advance for your help.

[WebrtcLogsLocalClient.txt](https://github.com/Microsoft/WebRTC-universal-samples/files/2851039/WebrtcLogsLocalClient.txt)
[WebrtcLogsUnityClient.txt](https://github.com/Microsoft/WebRTC-universal-samples/files/2851040/WebrtcLogsUnityClient.txt)

**Comment by anders-lundgren** [comment]
From the logs it appears as if you're building using Unity 2017.2.13? If you can, try building the project with a more recent version of Unity. I've found that it works if you use 2018.3.4f1 or newer.

**Comment by TomaszWozniakMosina** [comment]
Thanks!
I made it run finally. The solution was to change resolution of the local client...
