### ISSUE TITLE
AppRTC doesn't run in the background

### ISSUE THREAD

**Issue by timothy003** [Microsoft/WebRTC-universal-samples#7]
There are currently no examples or documentation on how to get WebRTC to work in the background in JS. Without this, audio is interrupted when the user switches away from the app or turns off the screen. Ideally, this would be done transparently by the library, with little or no changes to the app, allowing existing web apps like AppRTC to provide a good voice chat experience on platforms missing native WebRTC support.

**Comment by jamescadd** [comment]
Hi @timothy003, you are correct that we did not intend AppRTC to run in the background.  UWP is currently undergoing changes to move from the older 2 process model to a single process model per the following documentation https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/  We are waiting to do further development on background processing samples until this model is available to our apps.  If you feel like there is a more urgent need please reach out to jacadd@microsoft.com and let me know.

Thanks,
James

**Comment by timothy003** [comment]
Thanks, @jamescadd. I discovered that using the GameChat audio category for the audio clients apparently allows the process to run in the background on Desktop, even in connected standby. Is that intended? If so, I need to make it work on Mobile.

**Comment by jamescadd** [comment]
@timothy003 I would recommend using the voipCall capability to keep the app running in the background, but you may want to test both options.  Regarding running on connected standby, my understanding is that the machine shouldn't enter that state if the app is running in the background (it should stay powered up), and that if you need to wake a machine in that state via your app you can do so with a [SocketActivityTrigger](https://docs.microsoft.com/en-us/uwp/api/Windows.ApplicationModel.Background.SocketActivityTrigger).  All of those things work on Mobile as well, though I haven't tested that AppRTC reliably stays within the background process memory limits on Mobile.  Our ChatterBox sample does all of the above, but I would caveat that by saying that the sample is a bit complicated.  If you need any specific help there feel free to send me an email.  Hope that helps.
