### ISSUE TITLE
Is this project DEAD?

### ISSUE THREAD

**Issue by manjia** [Microsoft/WebRTC-universal-samples#9]
This project is clearly a scratch, making it work is quite hard and once we done that the connection is VERY unreliable even using it under the same gigabit LAN, I see no one is answering to issues nor providing documentation, should this sample be considered dead? If so you should close it to encourage people trying other approaches and to make people avoid wasting time trying here

**Comment by jamescadd** [comment]
Hi Manija, sorry for the slow response.  Which sample is giving you connection issues?  Fair criticism on the lack of documentation.  I'm working on adding our project plans to the repo which include a merger with Chrome M58 which is currently underway, followed by M61 & 63 in the coming months.  Most of our development takes place on the main repo here if you want the latest: https://github.com/webrtc-uwp

**Comment by manjia** [comment]
Ok, first of all your apologies are not accepted, what do you think we are doing here? combing dolls? as well as any company in the world mine needs to deliver products to customers,  and of course IF we had a question we could not afford to wait 3 months to get a feedback. 

Second, what in the world makes you think I do give a f*ck about what you are doing with your merger or whatever? What is that "oh I am planning to do cool stuff with my merger" assertion meant to? cheap advertising? Well I don't give a f*ck  about it, and neither does anybody else.

**Comment by jamescadd** [comment]
I've updated our documentation to point to the main development repo https://github.com/webrtc-uwp  PeerConnection sample has been posted here as well and included the Chromium M58 version of the WebRTC source https://github.com/Microsoft/WebRTC-universal-samples/tree/master/Samples/PeerCC-Sample

Thanks,
James
